name: npm publish CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Run Clear Install of Dependencies
        run: npm ci

      - name: Run Typescript Compiler
        run: npx tsc

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
